// let p = new Promise ((resolve, reject)=>{
//     let a = 1+3
//     if (a == 2){
//        resolve('Success')
//     }
//     else{
//         reject("Failed")
//     }
// })
// p.then((message)=> {
//     console.log('This is the then '  + message)
// }).catch((message) =>{
//     console.log("This is the  catch " + message)
// })
// async function getWeather() {
//     try {
//       const response = await fetch("https://api.weather.com/today");
//       const data = await response.json();
//       console.log("Weather today:", data);
//     } catch (error) {
//       console.log("Error getting weather:", error);
//     }
//   }
const promise = new Promise((resolve, reject)=>
    promise = true
if(promise ==true){
console.log("This passes " + message)
}
)
  